//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cursomvcapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallefactura
    {
        public int id { get; set; }
        public string numfactura { get; set; }
        public string codarticulo { get; set; }
        public int cantidad { get; set; }
        public decimal preciounitario { get; set; }
        public decimal total { get; set; }
    }
}
